# docker-compose.yml
version: "3"
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=giga2532933
      - POSTGRES_DB=postgres
    ports:
      - "5432"
